apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/config/kubeconfig
              subPath: kubeconfig
              name: kubeconfig
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
  namespace: moreillon
spec:
  ports:
    - port: 3000
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
